export const ERROR = {
  CODE_EXPIRED: 'CODE_EXPIRED',
  EMAIL_ALREADY_EXIST: 'EMAIL_ALREADY_EXIST',
  INVALID_CODE: 'INVALID_CODE',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND'
};